# General settings #
# ---------------- #

spring.application.name=simple-soap-client

# Server configuration #
# -------------------- #

# The server uses port 8080, so use 8081
server.port=8081
server.servlet.context-path=/

# Jetty-specific settings #
# ----------------------- #

server.jetty.threads.acceptors=2
server.jetty.threads.selectors=4
server.jetty.threads.max=200
server.jetty.threads.min=10
server.jetty.threads.idle-timeout=60000

# Connection settings #
# ------------------- #

server.jetty.connection-idle-timeout=30000
